### PR TITLE
Card section

### PR DESCRIPTION
**Pull request by John-pels**
done-card
done-card2

### CODE REVIEW

**Comment by John-pels** [comment]
That's how I have been doing it. Am I getting it wrong?

**Comment by John-pels** [comment]
Sorry, what's LGTM?

**Comment by SEUNAGBEYE** [comment]
Ah, my bad. It means `Looks good to me`.

**Comment by John-pels** [comment]
Oh, pardon me for my locality.
I will work on the origin URL on Monday and create a new PR.

**Pull request closed without merging**
