### PR TITLE
Our services

### PR DESCRIPTION
**Pull request by samynaj**
# Description

Fork and clone the repository,create a branch for your whatever you wanna work on, then add, commit and push to your forked repository and create a PR. Do ensure there is no conflict in your PR. Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Fixes # (issue)

# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [- ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] YES
- [ ] NO

# Checklist:

- [- ] My code follows the style guidelines of this project
- [- ] I have performed a self-review of my own code
- [- ] I followed the Sass 7-1 Architecture
- [- ] My changes generate no conflicts
- [
Screenshot (20)
Screenshot (19)
Screenshot (20)

 ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have tested my changes and it worked very fine

### CODE REVIEW

**Comment by John-pels** [comment]
Remove margin-top and margin-bottom from the main container to take the entire screen
sam's our-service2
sam's our-service

**Comment by John-pels** [comment]
Also, remove the margin-left and right from the <div class="container"></div> to take the entire screen. Let there be no whitespaces around the container, you can check the below screenshot

new service

**Comment by SEUNAGBEYE** [comment]
Centralize the content of this component
Screen Shot 2019-10-02 at 10 05 59 AM

**Comment by SEUNAGBEYE** [comment]
Also, why do you have `about-header.html`?

**Pull request merged**
